# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

palette:
  white: "#F7F6F2"
  black: "#20201D"
  red: "#F3535E"
  green: "#3EF47B"
  pink: "#FFC2C6"
  grey: "#666666"

final_space: true
version: 4
accent_color: "#ffc2c6"

# Maps users / hosts to custom strings
maps:
  user_name:
    tom: ⚡
  host_name:
    10.0.0.1: PVE
    10.0.0.2: Big Chungus

# The actual stuff to display
blocks:
  # Left hand side
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: os
        style: plain
        template: "{{ .Icon }} "
        foreground: p:white
      - type: session
        style: plain
        foreground: p:white
        template: "{{ if .SSHSession }}\ueba9{{ .UserName }}@{{ .HostName }}  {{ end }} "
      - type: path
        style: plain
        template: "[{{ .Path }}] "
        foreground: p:red
        options:
          home_icon: "\uf015"
      - type: git
        style: plain
        foreground: p:white
        template: "[{{.RepoName}}] "
      - type: project
        style: plain
        foreground: p:white
        template: "[{{ if .Error }}{{ .Error }}{{ else }}{{ if .Version }}{{.Version}}{{ end }} {{ if .Name }}{{ .Name }}{{ end }}{{ end }}] "
      - type: python
        style: plain
        foreground: p:white
        template: "[ {{ .Full }}] "
      - type: node
        style: plain
        foreground: p:white
        template: "[ {{ .Full }}] "

  # Right hand side
  - type: prompt
    alignment: right
    segments:
      - type: executiontime
        style: plain
        foreground: p:white
        template: " <#fefefe></> {{ .FormattedMs }} "
      - type: time
        style: plain
        foreground: p:white
        options:
          time_format: 15:04

  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: text
        foreground: "p:green"
        "foreground_templates": ["{{ if gt .Code 0 }}p:red{{ end }}"]
        style: plain
        template: "❯"
